{ pkgs, hycov, ... }:
{
  home.file = {
    ".config/hypr/images" = { source = ./images; recursive = true; };
  };

  imports = [
    ./configs/bind.nix
    ./configs/input.nix
    ./configs/layouts.nix
    ./configs/misc.nix
    ./configs/rules.nix
    ./configs/general.nix
    ./configs/animations.nix
    ./configs/decorations.nix
    ./configs/plugins.nix
  ];

  home.packages = with pkgs; [
    hyprpicker
    hyprshot
    hyprwayland-scanner
    iio-sensor-proxy
    wayland-scanner
    wl-clipboard
    wl-clip-persist
    wlr-protocols
  ];

  wayland.windowManager.hyprland = {
    systemd.enable = false; # <- false when using UWSM
    enable = true;
    plugins = with pkgs; [
      hyprlandPlugins.hypr-dynamic-cursors
    ];
    portalPackage = pkgs.xdg-desktop-portal-hyprland;
    extraConfig = "
      autogenerated = 0
      monitor = eDP-1, 1920x1200@60, 0x0, 1
      monitor = HDMI-A-1, 2560x1440@99.95, -2560x0, 1
    ";
    settings = {
      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$shell" = "zsh";
      "$menu" = "rofi";
      "$editor" = "nvim";
      exec-once = [
        #"systemctl --user start hyprpolkitagent"
        "bluetoothctl system-alias furcom-Laptop" # <- Bluetooth name visible to others
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "wl-clip-persist --clipboard regular"
      ];
      source = [ "~/.config/hypr/hypr_colors.conf" ];
    };
    sourceFirst = true;
    xwayland.enable = true;
  };
}
