{ pkgs, hycov, ... }:
{
  home.file = {
    ".config/hypr/images" = { source = ./images; recursive = true; };
    ".config/hypr/scripts" = { source = ./scripts; recursive = true; };
  };

  imports = [
    ./configs/bind.nix
    ./configs/input.nix
    ./configs/layouts.nix
    ./configs/misc.nix
    ./configs/rules.nix
    ./configs/general.nix
    ./configs/animations.nix
    ./configs/decorations.nix
    ./configs/plugins.nix
  ];

  home.packages = with pkgs; [
    cliphist
    hyprcursor
    hyprpicker
    hyprshot
    hyprsunset
    hyprwayland-scanner
    iio-sensor-proxy
    wallust
    wayland-scanner
    waypaper
    wl-clipboard
    wl-clip-persist
    wlr-protocols
  ];

  wayland.windowManager.hyprland = {
    systemd.variables = ["--all"];
    enable = true;
    package = pkgs.hyprland;
    portalPackage = pkgs.xdg-desktop-portal-hyprland;
    plugins = with pkgs; [
      hyprlandPlugins.hyprscroller
      hyprlandPlugins.hypr-dynamic-cursors
    ];
    extraConfig = "
      autogenerated = 0
      monitor = eDP-1, 1920x1200@60, 0x0, 1
      monitor = HDMI-A-1, 2560x1440@99.95, -2560x0, 1
    ";
    settings = {
      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$shell" = "zsh";
      "$menu" = "rofi";
      "$editor" = "nvim";
      exec-once = [
        #"systemctl --user start hyprpolkitagent"
        "hyprctl setcursor Bibata-Modern-Ice 32"
        "hyprpaper"
        "hyprpanel"
        "hyprsunset"
        "bluetoothctl power off"
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "wl-clip-persist --clipboard regular"
      ];
      env = [
        "HYPRCURSOR_THEME,Bibata-Modern-Ice"
        "HYPRCURSOR_SIZE,32"
        "HYPRSHOT_DIR, $HOME/Pictures/Screenshots"
      ];
      source = [
        "$HOME/.config/hypr/hypr_colors.conf"
      ];
    };
  };
}
