# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝
# config by furcom (https://github.com/furcom)

windowrulev2 = bordercolor $color3 0deg, fullscreen:1
windowrulev2 = bordersize 8, fullscreen:1

windowrulev2 = float, initialClass:it.mijorus.smile
windowrulev2 = size 19% 25%, initialClass:it.mijorus.smile
windowrulev2 = move 1526 814, initialClass:it.mijorus.smile

windowrulev2 = float, initialClass:Bitwarden
windowrulev2 = size 910 1041, initialClass:Bitwarden
windowrulev2 = move 945 114, initialClass:Bitwarden

windowrulev2 = float, initialClass:nemo
windowrulev2 = size 50% 55%, initialClass:nemo
windowrulev2 = center, initialClass:nemo

windowrulev2 = float, initialClass:waypaper
windowrulev2 = size 43% 62%, initialClass:waypaper
windowrulev2 = center, initialClass:waypaper

windowrulev2 = float, initialClass:nwg-look
windowrulev2 = size 43% 62%, initialClass:nwg-look
windowrulev2 = center, initialClass:nwg-look
