#!/bin/sh
# ███████╗███████╗████████╗████████╗██╗███╗   ██╗ ██████╗ ███████╗
# ██╔════╝██╔════╝╚══██╔══╝╚══██╔══╝██║████╗  ██║██╔════╝ ██╔════╝
# ███████╗█████╗     ██║      ██║   ██║██╔██╗ ██║██║  ███╗███████╗
# ╚════██║██╔══╝     ██║      ██║   ██║██║╚██╗██║██║   ██║╚════██║
# ███████║███████╗   ██║      ██║   ██║██║ ╚████║╚██████╔╝███████║
# ╚══════╝╚══════╝   ╚═╝      ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝
# ███╗   ███╗███████╗███╗   ██╗██╗   ██╗
# ████╗ ████║██╔════╝████╗  ██║██║   ██║
# ██╔████╔██║█████╗  ██╔██╗ ██║██║   ██║  script by furcom
# ██║╚██╔╝██║██╔══╝  ██║╚██╗██║██║   ██║  https://github.com/furcom
# ██║ ╚═╝ ██║███████╗██║ ╚████║╚██████╔╝
# ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝ ╚═════╝

###################################################
#################### Variables ####################
###################################################

# Monitor
MONITOR=$(hyprctl monitors | grep Monitor | awk '{print $2}')

# General
CFGDIR="$HOME/hypnix/home/configs"
CacheDir="$HOME/.cache"
EDITOR="vim"
TERMINAL="kitty"

# fusuma
FusumaDir="$CFGDIR/fusuma"
FusumaScriptsDir="$FusumaDir/scripts"

# Hypr Ecosystem
HyprDir="$CFGDIR/hypr"
HyprScriptsDir="$HyprDir/scripts"
HyprConfigsDir="$HyprDir/configs"
HyprImagesDir="$HyprDir/images/"
HyprWallpapersDir="$HyprImagesDir/Wallpapers"

# kitty
KittyDir="$CFGDIR/kitty"
KittyConfigsDir="$KittyDir/configs"

# rofi
RofiDir="$CFGDIR/rofi"
RofiScriptsDir="$RofiDir/scripts"
RofiMenu="rofi -dmenu -config $RofiDir/config.rasi"
RofiMenuSettings="rofi -dmenu"

# wallust
WallustDir="$CFGDIR/wallust"
WallustTemplatesDir="$WallustDir/templates"

# hyprpanel
HyprpanelDir="$CFGDIR/hyprpanel"

###################################################
#################### Functions ####################
###################################################

main_menu() {
  OPTIONS=" Hyprland\n󰸉 Wallpaper\n󰏖 Packages\n Extras\n󰅙 Exit"
  CHOICE=$(echo -e "$OPTIONS" | $RofiMenuSettings -selected-row $SelectedRowMain)

  if [ -z "$CHOICE" ]; then
    exit 0
  fi

  if [ -z "$CHOICE" ]; then
    main_menu
  elif [ "$CHOICE" == "󰅙 Exit" ]; then
    exit 0
  else
    case "$CHOICE" in
      " Hyprland")
        hyprland_menu ;;
      "󰸉 Wallpaper")
        waypaper ;;
      " Extras")
        extras_menu ;;
      "󰏖 Packages")
        packages_menu ;;
      *)
        echo "Invalid choice" ;;
    esac
  fi
}

hyprland_menu() {
  HYPRLAND_OPTIONS="󰤺 Animations\n Bindings\n Colors (Wallust)\n󰈙 Config\n󰇀 Cursor\n Decorations\n General\n󰍽 Input\n Layouts\n Misc\n Plugins\n Rules\n󱞲 Back"
  HYPRLAND_SUBCHOICE=$(echo -e "$HYPRLAND_OPTIONS" | $RofiMenuSettings -selected-row $SelectedRowHypr)

  if [ -z "$HYPRLAND_SUBCHOICE" ]; then
    SelectedRowMain="0"
	  main_menu
      elif [ "$HYPRLAND_SUBCHOICE" == "󱞲 Back" ]; then
        SelectedRowMain="0"
        main_menu
      else
      case "$HYPRLAND_SUBCHOICE" in
        "󰤺 Animations") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/animations.conf" ;;
        " Bindings") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/bindings.conf" ;;
        " Colors (Wallust)") $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/hyprland";;
        "󰈙 Config") $TERMINAL sh -c "$EDITOR $HyprDir/hyprland.conf" ;;
        "󰇀 Cursor") $TERMINAL sh -c "$HyprScriptsDir/cursor" ;;
        " Decorations") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/decorations.conf" ;;
        " General") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/general.conf" ;;
        "󰍽 Input") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/input.conf" ;;
        " Layouts")
          LAYOUTS_OPTIONS="󰈙 Config\n󰕴 Dwindle\n󰯌 Master\n󱞲 Back"
		      LAYOUTS_SUBCHOICE=$(echo -e "$LAYOUTS_OPTIONS" | $RofiMenuSettings)
		        case "$LAYOUTS_SUBCHOICE" in
			        "󰈙 Config") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/layouts.conf" ;;
	            "󰕴 Dwindle") $HyprScriptsDir/layouts --dwindle ;;
	            "󰯌 Master") $HyprScriptsDir/layouts --master ;;
			        "󱞲 Back"|"")
                SelectedRowMain="0"
                SelectedRowHypr="4"
			          hyprland_menu ;;
		        esac ;;
        " Misc") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/misc.conf" ;;
        " Plugins")
          PLUGINS_OPTIONS="󰈙 Config\n󰚰 Updates\n󱞲 Back"
          PLUGINS_SUBCHOICE=$(echo -e "$PLUGINS_OPTIONS" | $RofiMenuSettings)
          case "$PLUGINS_SUBCHOICE" in
            "󱞲 Back"|"")
              SelectedRowHypr="10"
              hyprland_menu ;;
            "󰈙 Config") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/plugins.conf" ;;
            "󰚰 Updates") $TERMINAL sh -c "$HyprScriptsDir/packages --hypr" ;;
          esac ;;
        " Rules") $TERMINAL sh -c "$EDITOR $HyprConfigsDir/rules.conf" ;;
      esac
  fi
}

packages_menu() {
  PACKAGES_OPTIONS="󰮯 Pacman Updates\n AUR Updates\n󰃢 Clean Pacman\n󱞲 Back"
  PACKAGES_SUBCHOICE=$(echo -e "$PACKAGES_OPTIONS" | $RofiMenuSettings)

  if [ -z "$PACKAGES_SUBCHOICE" ]; then
    SelectedRowMain="2"
    main_menu
  elif [ "$PACKAGES_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowMain="2"
    main_menu
  else
    case "$PACKAGES_SUBCHOICE" in
      "󰮯 Pacman Updates") $TERMINAL sh -c "$HyprScriptsDir/packages --pacman" ;;
      " AUR Updates") $TERMINAL sh -c "$HyprScriptsDir/packages --aur" ;;
      "󰃢 Clean Pacman") $TERMINAL sh -c "$HyprScriptsDir/packages --clean" ;;
    esac
  fi
}

extras_menu() {
  EXTRAS_OPTIONS="󰵷 Fusuma\n GTK Theming\n Hyprlock\n󱂩 Hyprpanel\n󰄛 Kitty\n Oh My Posh\n󰮫 Rofi\n Wallust\n󱞲 Back"
  EXTRAS_SUBCHOICE=$(echo -e "$EXTRAS_OPTIONS" | $RofiMenuSettings -selected-row $SelectedRowExtras)

  if [ -z "$EXTRAS_SUBCHOICE" ]; then
    SelectedRowMain="3"
    main_menu
  elif [ "$EXTRAS_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowMain="3"
    main_menu
  else
    case "$EXTRAS_SUBCHOICE" in
      "󰵷 Fusuma") fusuma_menu ;;
      " GTK Theming") nwg-look ;;
      " Hyprlock") $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/hyprlock" ;;
      "󱂩 Hyprpanel") hyprpanel_menu ;;
      "󰄛 Kitty") kitty_menu ;;
      " Oh My Posh") $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/oh-my-posh" ;;
      "󰮫 Rofi") rofi_menu ;;
      " Wallust") $TERMINAL sh -c "$EDITOR $WallustDir/wallust.toml" ;;
    esac
  fi
}

fusuma_menu() {
  FUSUMA_OPTIONS="󰈙 Config\n󰑓 Restart\n󱞲 Back"
  FUSUMA_SUBCHOICE=$(echo -e "$FUSUMA_OPTIONS" | $RofiMenuSettings)

  if [ -z "$FUSUMA_SUBCHOICE" ]; then
    SelectedRowExtras="0"
    extras_menu
  elif [ "$FUSUMA_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowExtras="0"
    extras_menu
  else
    case "$FUSUMA_SUBCHOICE" in
      "󰈙 Config") $TERMINAL sh -c "$EDITOR $FusumaDir/config.yml" ;;
      "󰑓 Restart") pkill fusuma && fusuma -d ;;
    esac
  fi
}

hyprpanel_menu() {
  HYPRPANEL_OPTIONS="󰈙 Config\n󰑓 Restart\n󱞲 Back"
  HYPRPANEL_SUBCHOICE=$(echo -e "$HYPRPANEL_OPTIONS" | $RofiMenuSettings)

  if [ -z "$HYPRPANEL_SUBCHOICE" ]; then
    SelectedRowExtras="3"
    extras_menu
  elif [ "$HYPRPANEL_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowExtras="3"
    extras_menu
  else
    case "$HYPRPANEL_SUBCHOICE" in
      "󰑓 Restart") hyprpanel -q; hyprpanel ;;
      "󰈙 Config" ) $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/hyprpanel" ;;
    esac
  fi
}

kitty_menu() {
  KITTY_OPTIONS="󰈙 Config\n Keymaps\n󰑓 Reload Config\n Style\n󱞲 Back"
  KITTY_SUBCHOICE=$(echo -e "$KITTY_OPTIONS" | $RofiMenuSettings)

  if [ -z "$KITTY_SUBCHOICE" ]; then
    SelectedRowExtras="4"
    extras_menu
  elif [ "$KITTY_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowExtras="4"
    extras_menu
  else
    case "$KITTY_SUBCHOICE" in
      "󰈙 Config") $TERMINAL sh -c "$EDITOR $KittyDir/kitty.conf" ;;
      " Keymaps") $TERMINAL sh -c "$EDITOR $KittyDir/keymaps.conf" ;;
      "󰑓 Reload Config") kill -SIGUSR1 $(pidof kitty) ;;
      " Style") $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/style.conf" ;;
    esac
  fi
}

rofi_menu() {
  ROFI_OPTIONS="󰈙 Config\n Colors (Wallust)\n󱞲 Back"
  ROFI_SUBCHOICE=$(echo -e "$ROFI_OPTIONS" | $RofiMenuSettings)

  if [ -z "$ROFI_SUBCHOICE" ]; then
    SelectedRowExtras="6"
    extras_menu
  elif [ "$ROFI_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowExtras="6"
    extras_menu
  else
    case "$ROFI_SUBCHOICE" in
      "󰈙 Config") $TERMINAL sh -c "$EDITOR $RofiDir/config.rasi" ;;
      " Colors (Wallust)") $TERMINAL sh -c "$EDITOR $WallustTemplatesDir/rofi" ;;
    esac
  fi
}

connections_menu() {
  CONNECTIONS_OPTIONS=" Bluetooth\n󰖩 WiFi\n󰖂 Wireguard\n󱞲 Back"
  CONNECTIONS_SUBCHOICE=$(echo -e "$CONNECTIONS_OPTIONS" | $RofiMenuSettings -selected-row $SelectedRowConnection)

  if [ -z "$CONNECTIONS_SUBCHOICE" ]; then
    SelectedRowMain="1"
    main_menu
  elif [ "$CONNECTIONS_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowMain="1"
    main_menu
  else
    case "$CONNECTIONS_SUBCHOICE" in
      " Bluetooth") $TERMINAL sh -c "rfkill unblock bluetooth && bluetui;" ;;
      "󰖩 WiFi") $TERMINAL sh -c "nmtui;" ;;
      "󰖂 Wireguard") wireguard_menu ;;
    esac
  fi
}

wireguard_menu() {
  WIREGUARD_OPTIONS="󰌘 Connect\n󰌙 Disconnect\n󰑓 Reconnect\n󰐥 Enable\n󰤂 Disable\n󱘖 Status\n󰈙 Config\n󱞲 Back"
  WIREGUARD_SUBCHOICE=$(echo -e "$WIREGUARD_OPTIONS" | $RofiMenuSettings)

  if [ -z "$WIREGUARD_SUBCHOICE" ]; then
    SelectedRowConnection="3"
    connections_menu
  elif [ "$WIREGUARD_SUBCHOICE" == "󱞲 Back" ]; then
    SelectedRowConnection="3"
    connections_menu
  else
    case "$WIREGUARD_SUBCHOICE" in
      "󰌘 Connect") $HyprScriptsDir/wireguard --connect ;;
      "󱘖 Status") $HyprScriptsDir/wireguard --status ;;
      "󰌙 Disconnect") $HyprScriptsDir/wireguard --disconnect ;;
      "󰑓 Reconnect") $HyprScriptsDir/wireguard --reconnect ;;
      "󰐥 Enable") $HyprScriptsDir/wireguard --enable ;;
      "󰤂 Disable") $HyprScriptsDir/wireguard --disable ;;
      "󰈙 Config") $HyprScriptsDir/wireguard --config ;;
    esac
  fi
}

#####################################################
#################### Main Script ####################
#####################################################

main_menu
