#!/usr/bin/env bash

displayLogo() {
  echo -e "\n\e[34m██╗  ██╗██╗   ██╗██████╗ ███╗   ██╗██╗██╗  ██╗\e[0m"
  echo -e "\e[34m██║  ██║╚██╗ ██╔╝██╔══██╗████╗  ██║██║╚██╗██╔╝\e[0m"
  echo -e "\e[34m███████║ ╚████╔╝ ██████╔╝██╔██╗ ██║██║ ╚███╔╝\e[0m"
  echo -e "\e[34m██╔══██║  ╚██╔╝  ██╔═══╝ ██║╚██╗██║██║ ██╔██╗\e[0m"
  echo -e "\e[34m██║  ██║   ██║   ██║     ██║ ╚████║██║██╔╝ ██╗\e[0m"
  echo -e "\e[34m╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝\e[0m"
  echo -e "\e[34m██╗   ██╗██████╗ ██████╗  █████╗ ████████╗███████╗███████╗\e[0m"
  echo -e "\e[34m██║   ██║██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔════╝\e[0m"
  echo -e "\e[34m██║   ██║██████╔╝██║  ██║███████║   ██║   █████╗  ███████╗\e[0m"
  echo -e "\e[34m██║   ██║██╔═══╝ ██║  ██║██╔══██║   ██║   ██╔══╝  ╚════██║\e[0m"
  echo -e "\e[34m╚██████╔╝██║     ██████╔╝██║  ██║   ██║   ███████╗███████║\e[0m"
  echo -e "\e[34m ╚═════╝ ╚═╝     ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝╚══════╝\e[0m"
  echo -e "\e[34m      script by furcom (https://github.com/furcom)\n\e[0m"
}

FLAKE_DIR="$HOME/hypnix"
BUILD_DIR="$FLAKE_DIR/result"

TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_FILE="$HOME/flake.lock_BACKUP_$TIMESTAMP"

checkUpdates() {
  if [ ! -f "$FLAKE_DIR/flake.nix" ]; then
      echo "Error: No Flake configuration found in $FLAKE_DIR"
      echo ""
      exit 1
  fi
  
  cd "$FLAKE_DIR" || exit 1

  nixos-rebuild build --flake "$FLAKE_DIR/#hypnix" &> /dev/null
  
  if [ ! -e "$BUILD_DIR" ]; then
      echo "Error: Build failed."
      echo ""
      exit 1
  fi
  
  UPDATE_COUNT=$(nvd diff /run/current-system "$BUILD_DIR" | awk '/->/ {count++} END {print count}')
  
  if [ -z "$UPDATE_COUNT" ]; then
      UPDATE_COUNT=0
  fi
  
  echo "$UPDATE_COUNT"
  
  rm -rf "$BUILD_DIR"
}

case "$1" in
  -c)
    checkUpdates
  ;;
  -cx)
    clear
    displayLogo
    echo -e "\nChecking...\n"
    echo -e "$(checkUpdates) available update(s)\n"
    read -p "Press any key to exit..."
  ;;
  -u)
    clear
    displayLogo
    update_packages
  ;;
  *)
    echo -e ""
  ;;
esac
