{ pkgs, ... }:
{
  home.file = {
    ".config/hypr/images" = { source = ./images; recursive = true; };
    ".config/hypr/scripts" = { source = ./scripts; recursive = true; };
  };

  imports = [
    ./configs/bind.nix
    ./configs/input.nix
    ./configs/layouts.nix
    ./configs/misc.nix
    ./configs/rules.nix
    ./configs/general.nix
    ./configs/animations.nix
    ./configs/decorations.nix
    ./configs/plugins.nix
  ];

  home.packages = with pkgs; [
    cliphist
    hyprcursor
    hypridle
    hyprpicker
    hyprshot
    hyprsunset
    hyprwayland-scanner
    iio-sensor-proxy
    wallust
    wayland-scanner
    waypaper
    wl-clipboard
    wl-clip-persist
    wlr-protocols
  ];

  programs = {
    hyprlock = { enable = true; package = pkgs.hyprlock; };
  };

  services = {
    hypridle = {
      enable = true;
      package = pkgs.hypridle;
      importantPrefixes = [ "$" ];
      settings = {
        general = {
          after_sleep_cmd = "hyprctl dispatch dpms on";
          ignore_dbus_inhibit = false;
          lock_cmd = "hyprlock";
        };
        listener = [
          { timeout = 900; on-timeout = "hyprlock"; }
          { timeout = 1200; on-timeout = "hyprctl dispatch dpms off"; on-resume = "hyprctl dispatch dpms on"; }
        ];
      };
    };
  };

  wayland.windowManager.hyprland = {
    systemd.variables = ["--all"];
    enable = true;
    package = pkgs.hyprland;
    portalPackage = pkgs.xdg-desktop-portal-hyprland;
    plugins = [
      pkgs.hyprlandPlugins.hyprscroller
      pkgs.hyprlandPlugins.hypr-dynamic-cursors
    ];
    extraConfig = "
      autogenerated = 0
      monitor = eDP-1, 1920x1200@60, 0x0, 1
    ";
    settings = {
      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$shell" = "zsh";
      "$webbrowser" = "google-chrome-stable";
      "$lockscreen" = "hyprlock";
      "$filemanager" = "nemo";
      "$menu" = "rofi";
      "$editor" = "nvim";
      exec-once = [
        "systemctl --user start hyprpolkitagent"
        "hyprlock"
        "hyprctl setcursor Bibata-Modern-Ice 32"
        "bluetoothctl power off"
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "wl-clip-persist --clipboard regular"
        "hyprpaper"
        "hyprpanel"
        "hypridle"
      ];
      env = [
        "HYPRCURSOR_THEME,Bibata-Modern-Ice"
        "HYPRCURSOR_SIZE,32"
        "HYPRSHOT_DIR, $HOME/Pictures/Screenshots"
      ];
      source = [
        "$HOME/.config/hypr/hypr_colors.conf"
      ];
    };
  };
}
