{ inputs, config, pkgs, ... }:
{
  home.file = {
    ".config/hypr/images" = { source = ./images; recursive = true; };
    ".config/hypr/scripts" = { source = ./scripts; recursive = true; };
    ".config/hypr/hyprpaper.conf" = { source = ./hyprpaper.conf; };
  };
  imports = [
    ./configs/bind.nix
    ./configs/input.nix
    ./configs/layouts.nix
    ./configs/misc.nix
    ./configs/rules.nix
    ./configs/general.nix
    ./configs/animations.nix
    ./configs/decorations.nix
    ./configs/plugins.nix
  ];
  wayland.windowManager.hyprland = {
    systemd.variables = ["--all"];
    enable = true;
    package = pkgs.hyprland;
    portalPackage = pkgs.xdg-desktop-portal-hyprland;
    plugins = [
      pkgs.hyprlandPlugins.hyprexpo
      pkgs.hyprlandPlugins.hypr-dynamic-cursors
    ];
    extraConfig = "
      autogenerated = 0
      monitor = eDP-1, 1920x1200@60, 0x0, 1
    ";
    settings = {
      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$shell" = "zsh";
      "$webbrowser" = "google-chrome-stable";
      "$lockscreen" = "hyprlock";
      "$filemanager" = "nemo";
      "$menu" = "rofi";
      "$editor" = "nvim";
      exec-once = [
        "hyprctl setcursor Bibata-Modern-Ice 32"
        "systemctl --user start hyprpolkitagent"
        "bluetoothctl power off"
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
        "wl-clip-persist --clipboard regular"
        "hyprpaper"
        "hyprpanel"
        "#fusuma"
        "hypridle"
      ];
      env = [
        "HYPRCURSOR_THEME,Bibata-Modern-Ice"
        "HYPRCURSOR_SIZE,32"
        "HYPRSHOT_DIR, $HOME/Pictures/Screenshots"
      ];
      source = [
        "$HOME/.config/hypr/hypr_colors.conf"
      ];
    };
  };
}
